### PR TITLE
Suggestion: Implementation of the "Undo" functionality

### PR DESCRIPTION
**Pull request by Shark-vil**
Functionality:
- Class for creating custom undo list
- Class for invoking the undo action
- Global events "OnUndo" and "OnFinishUndo" for the class - "Undo"
- Local events "OnUndo" and "OnFinishUndo" for the class - "UndoEntry"
- Added several examples of using the "Undo" and "UndoEntry" classes

### CODE REVIEW

**Comment by Shark-vil** [comment]
P.s. I am told that this functionality has already been implemented, but I could not find it. Explain if I do not understand something. 🤔

**Comment by Shark-vil** [comment]
**Demonstration:**
https://www.youtube.com/watch?v=eamugHweUK8

**Comment by Shark-vil** [comment]
Too very bad implementation? 🤔

**Comment by aylaylay** [comment]
The sandbox gamemode is used by us to test things out, at some point there will be work done on a real sandbox mode. Accepting random features doesn't help us as we'd need to spend time looking through the code and maintaining it. These kinds of things should be put in your own gamemode, it doesn't need to be in this repo. Sorry.

**Comment by Shark-vil** [comment]
> The sandbox gamemode is used by us to test things out, at some point there will be work done on a real sandbox mode. Accepting random features doesn't help us as we'd need to spend time looking through the code and maintaining it. These kinds of things should be put in your own gamemode, it doesn't need to be in this repo. Sorry.

Ok, I understood.

**Pull request closed without merging**
