### PR TITLE
Add more construction Tools

### PR DESCRIPTION
**Pull request by SupinePandora43**
Adds those tools:
- [x] axis
- [x] ballsocket
- [x] nocollide
- [x] slider

### CODE REVIEW

**Comment by SupinePandora43** [comment]
Please review

**Comment by SupinePandora43** [comment]
Why?

**Comment by SupinePandora43** [comment]
Why @aylaylay ?

**Comment by aylaylay** [comment]
Put this in your own gamemode, we're not accepting PR's for this repo.

**Pull request closed without merging**
